name: nlp-api
dependencies:
- backports_abc=0.4=py27_0
- beautifulsoup4=4.4.1=py27_0
- bokeh=0.11.1=py27_0
- cycler=0.10.0=py27_0
- decorator=4.0.9=py27_0
- flask=0.10.1=py27_1
- flask-wtf=0.11=py27_0
- freetype=2.5.5=0
- futures=3.0.3=py27_0
- itsdangerous=0.24=py27_0
- jinja2=2.8=py27_0
- libpng=1.6.17=0
- markupsafe=0.23=py27_0
- matplotlib=1.5.1=np110py27_0
- mkl=11.3.1=0
- networkx=1.11=py27_0
- nltk=3.2=py27_0
- numpy=1.10.4=py27_0
- openssl=1.0.2g=0
- pandas=0.18.0=np110py27_0
- pip=8.1.0=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_1
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- pytz=2015.7=py27_0
- pyyaml=3.11=py27_1
- qt=4.8.7=1
- readline=6.2=2
- requests=2.9.1=py27_0
- scikit-learn=0.17.1=np110py27_0
- scipy=0.17.0=np110py27_0
- seaborn=0.7.0=py27_0
- setuptools=20.2.2=py27_0
- simplejson=3.8.2=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- snowballstemmer=1.2.1=py27_0
- sqlite=3.9.2=0
- ssl_match_hostname=3.4.0.2=py27_0
- tk=8.5.18=0
- tornado=4.3=py27_0
- werkzeug=0.11.4=py27_0
- wheel=0.29.0=py27_0
- wtforms=2.0.2=py27_0
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - astroid==1.3.6
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - cpplint==0.0.6
  - funcsigs==0.4
  - logilab-common==1.0.2
  - mercurial==3.6.3
  - mock==1.3.0
  - nose==1.3.7
  - pbr==1.8.1
  - protobuf==2.6.1
  - pygobject==3.18.2
  - pylint==1.4.4
  - stevedore==1.6.0
  - virtualenv==13.1.2
  - virtualenv-clone==0.2.6

